version: '3.8'

services:
  postgres:
    container_name: postgres_container_mii
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      
    ports:
      - "5432:5432"
    restart: always
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: always
